### ISSUE TITLE
Jukeboks Logo Proposal

### ISSUE THREAD

**Issue by moenawar85** [hirohisa/Jukeboks#22]
Hello Sir. Hirohisa... I would like to contribute with your project by created a new logo. If you like it I will give you original file that editable in CDR or PNG.
The final result is something like this
![jukeboks logo_final](https://user-images.githubusercontent.com/36834147/38670737-d5fdd25e-3e73-11e8-848c-88c719d009a7.png)

best regards, Moenawar.
Thank you indeed.

**Comment by hirohisa** [comment]
Thanks for your contribution!

I'm happy because It inherits my icon about color. I want to use your icon. Could you drag and drop your image ( 1024x1024, png ) to this issue ? 

Also, I will release new app with your image so write with links (Github, Twitter, Steemit ... ) that you wish to be added to the acknowledgements tab.

**Comment by moenawar85** [comment]
Yes ofcourse,
![jukeboks icon_1024px](https://user-images.githubusercontent.com/36834147/38744853-2125484e-3f6d-11e8-8d06-e9918b5b146d.png)
# 
![jukeboks icon_1024px_black](https://user-images.githubusercontent.com/36834147/38744862-29cfa480-3f6d-11e8-92e7-c279913bf9f2.png)
# 
![jukeboks_logo icon_color](https://user-images.githubusercontent.com/36834147/38744885-3b91138e-3f6d-11e8-8914-56fe0946a9fa.png)
# 
![jukeboks_logo icon_black](https://user-images.githubusercontent.com/36834147/38744896-42ea01b8-3f6d-11e8-9a6e-ba29a3a220b8.png)

**Comment by moenawar85** [comment]
My github link: https://github.com/moenawar85 
my twitter @moen85 and 
my steemit; https://steemit.com/@moenawar

**Comment by moenawar85** [comment]
Here is PDF file and PNG (Logo Icon, logotype and typography)
https://drive.google.com/folderview?id=1Xf24JjCespF1SwoP_78PLG-pHXJ-KGYK

**Comment by hirohisa** [comment]
Thank you for your design 🎉 
I released new app.

- https://github.com/hirohisa/Jukeboks/releases/tag/1.4.0
- https://github.com/hirohisa/Jukeboks/blob/master/Acknowledgements.md
- https://github.com/hirohisa/Jukeboks/tree/master/assets

**Comment by moenawar85** [comment]
you are welcome sir :)


2018-04-14 10:05 GMT+07:00 Hirohisa Kawasaki <notifications@github.com>:

**Comment by moenawar85** [comment]
I posted this logo on Utopian platform with steem connect. Here is the link https://steemit.com/utopian-io/@moenawar/my-new-logo-design-proposal-for-jukeboks
